# Generated by Django 2.0.8 on 2019-01-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('home', '0008_homepage2_homepage3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage2',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage3',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='HomePage2',
        ),
        migrations.DeleteModel(
            name='HomePage3',
        ),
    ]
